---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: forbid-yml
        name: Forbid .yml file extensions (use .yaml)
        entry: YAML file extensions must be .yaml
        language: fail
        files: \.yml$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes
      - id: fix-ligatures
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        args:
          - --ignore-unknown
          # - "--ignore-path '**/*.md'"
          # - "--ignore-path '**/*.y*ml'"

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0 # v0.30.0
    hooks:
      - id: markdownlint
        args:
          - --config=.markdownlint.yaml
          - --fix
  # Lint: YAML
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args:
          - --config-file=.yamllint.yaml
          - --format=parsable
          - --strict
  # Lint & Format: Python
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.257"
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  # Lint: Dockerfile with system hadolint
  # - repo: https://github.com/petalmd/dockerfile-pre-commit
  #   rev: v1.0
  #   hooks:
  #     - id: dockerlint
  #       # args: [--ignore, DL3025, --ignore, DL3018]
  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: [dockerfile]
        entry: hadolint

  # Lint: Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        args: [-x]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - "-L"
          - "keypair"
