# docker-compose.from-jupyter.yml
# ref: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose
# ref: https://vgarcia.dev/blog/2019-06-17-building-docker-images-using-docker-compose-and-gitlab/
version: "3.7"

services:
  base_env:
    build:
      context: ./src/base_env/
      args:
        BASE_IMAGE: jupyter/minimal-notebook
        PYTHON_VERSION: 3.8.*
    image: base_env:python-3.8

  # general datasci image
  ds_env:
    build:
      context: ./src/ds_env/
      args:
        BASE_IMAGE: ninerealmlabs/base_env:python-3.8
        PYTHON_VERSION: 3.8.*
    image: ds_env:python-3.8
    depends_on:
      - base_env

  nlp_env:
    build:
      context: ./src/nlp_env/
      args:
        BASE_IMAGE: ninerealmlabs/ds_env:python-3.8
        PYTHON_VERSION: 3.8.*
    image: nlp_env:python-3.8
    depends_on:
      - ds_env

  pytorch_env:
    build:
      context: ./src/pytorch_env/
      args:
        BASE_IMAGE: ninerealmlabs/ds_env:python-3.8
        PYTHON_VERSION: 3.8.*
    image: pytorch_env:python-3.8
    depends_on:
      - ds_env

  web_env:
    build:
      context: ./src/web_env/
      args:
        BASE_IMAGE: ninerealmlabs/ds_env:python-3.8
        PYTHON_VERSION: 3.8.*
    image: web_env:python-3.8
    depends_on:
      - ds_env


  forecast_env:
    build:
      context: ./src/forecast_env/
      args:
        BASE_IMAGE: ninerealmlabs/pytorch_env:python-3.8
        PYTHON_VERSION: 3.8.*
    image: forecast_env:python-3.8
    depends_on:
      - pytorch_env