# docker-compose.from-jupyter.yml
# ref: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose
# ref: https://vgarcia.dev/blog/2019-06-17-building-docker-images-using-docker-compose-and-gitlab/
version: "3.7"

services:
  # base image for PMI projects
  base_env:
    build:
      context: ./src/base_env/
      args:
        BASE_IMAGE: jupyter/minimal-notebook
        PYTHON_VERSION: ${PYTHON_VERSION}
        BUILD_DATE: ${DATE}
    image: base_env:${PYTHON_VERSION}              # provide a name and tag for the image

  # general datasci image
  ds_env:
    build:
      context: ./src/ds_env/
      args:
        BASE_IMAGE: base_env:${PYTHON_VERSION}
        BUILD_DATE: ${DATE}
      cache_from:
        - base_env:${PYTHON_VERSION}
    image: ds_env:${PYTHON_VERSION}              # provide a name and tag for the image
    depends_on:                       # specify dependencies for build
      - base_env

  # project-specific images
  clv_env:
    build:
      context: ./src/clv_env/
      args:
        BASE_IMAGE: ds_env:${PYTHON_VERSION}
        BUILD_DATE: ${DATE}
      cache_from:
        - ds_env:${PYTHON_VERSION}
    image: clv_env:${PYTHON_VERSION}       # provide a name and tag for the image
    depends_on:                       # specify dependencies for build
      - ds_env

  forecast_env:
    build:
      context: ./src/forecast_env/
      args:
        BASE_IMAGE: ds_env:${PYTHON_VERSION}
        BUILD_DATE: ${DATE}
      cache_from:
        - pytorch_env:${PYTHON_VERSION}
    image: forecast_env:${PYTHON_VERSION}  # provide a name and tag for the image
    depends_on:                       # specify dependencies for build
      - pytorch_env

  pytorch_env:
    build:
      context: ./src/pytorch_env/
      args:
        BASE_IMAGE: ds_env:${PYTHON_VERSION}
        BUILD_DATE: ${DATE}
      cache_from:
        - ds_env:${PYTHON_VERSION}
    image: pytorch_env:${PYTHON_VERSION}  # provide a name and tag for the image
    depends_on:                       # specify dependencies for build
      - ds_env

  nlp_env:
    build:
      context: ./src/nlp_env/
      args:
        BASE_IMAGE: ds_env:${PYTHON_VERSION}
        BUILD_DATE: ${DATE}
      cache_from:
        - ds_env:${PYTHON_VERSION}
    image: nlp_env:${PYTHON_VERSION}     # provide a name and tag for the image
    depends_on:                       # specify dependencies for build
      - ds_env

  web_env:
    build:
      context: ./src/web_env/
      args:
        BASE_IMAGE: ds_env:${PYTHON_VERSION}
        BUILD_DATE: ${DATE}
        # CHROMEDRIVER: "https://chromedriver.storage.googleapis.com/92.0.4515.43/chromedriver_linux64.zip"
      cache_from:
        - ds_env:${PYTHON_VERSION}
    image: web_env:${PYTHON_VERSION}     # provide a name and tag for the image
    depends_on:                       # specify dependencies for build
      - ds_env
