---
name: jupyterlab
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - black
  - colorama
  - markdown
  - numba
  - numpydoc
  - openpyxl
  - pep8
  - pep8-naming
  - protobuf
  - pycodestyle
  - pylint
  - pytest
  - python-dateutil
  - python-dotenv
  - pyyaml
  ### docker image tests; also in 'requirements-dev.txt'
  # - docker
  - plumbum
  # - pre-commit
  # # `pytest-xdist` is a plugin that provides the `--numprocesses` flag,
  # # allowing us to run `pytest` tests in parallel
  # - pytest-xdist
  - requests
  - ruff
  - tabulate
  - pip:
      - docker
