# docker-compose..yml
version: "3.7"

services:
  nlp_env:
    build:
      context: .
      args:
        BASE_IMAGE: ds_env
      cache_from:
        - ds_env:latest
    image: nlp_env:latest     # provide a name and tag for the image
    ports:
      - "8888:8888"
    # user: root
    environment:
      # - NB_USER=${NB_USER}
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      # - JUPYTER_TOKEN=jupyter_notebook_token
    command: start.sh jupyter lab

  # volumes:  # Optional, same as `docker volume create`

  # networks:  # Optional, same as `docker network create`

### build command
# docker build . --no-cache --build-arg BASE_IMAGE="ds_env" --build-arg BUILD_DATE=$(date +'%Y-%m-%d') -t nlp_env:latest
# docker build https://github.com/docker/rootfs.git#container:docker --build-arg PYTHON_VERSION=3.8.8 --build-arg BUILD_DATE=$(date +'%Y-%m-%d')  -t nlp_env:latest
