---
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  ### package managers
  - mamba
  - pip
  ### core deps
  - cython
  - ipykernel
  - 'conda-forge::blas=*=openblas'
  ### data & ml
  - category_encoders
  - faker
  - dataprep
  - imbalanced-learn
  # - jenkspy
  - lightgbm
  - missingno
  - numexpr
  - numpy
  - pandas
  - patsy
  - pytables
  - scikit-image
  - scikit-learn
  - scipy
  - statsmodels
  - sympy
  - xarray
  - xgboost
  ### plotting
  - altair
  - bokeh
  - ipympl
  - ipywidgets
  - matplotlib-base
  - plotnine
  - plotly
  - widgetsnbextension
  ### utils
  - attrs
  - cloudpickle
  - colorama
  - dill
  - h5py
  - hdf5
  - joblib
  - markdown
  - openpyxl
  - protobuf
  - pyarrow
  - pyodbc
  - python-dateutil
  - pyyaml
  - sqlalchemy
  - tqdm
  - xlrd
# prefix: /opt/conda/
