---
name: save-artifact
description: save variables to artifact

inputs:
  image_name:
    description: Image name (future source_image)
    required: true
  python_version:
    description: Python version (<major.minor.*>)
    required: true
  python_tag:
    description: Python version tag (python-<major.minor>)
    required: true
  git_tag:
    description: Git short sha
    required: true
  image_digest:
    description: Image digest
    required: true

runs:
  using: composite
  steps:
    - name: Save outputs to artifacts 💾
      id: outputs
      shell: bash
      run: |
        mkdir -p ./outputs
        cat << EOF >> ./outputs/vars
          image_name "${{ inputs.image_name }}"
          python_version "${{ inputs.python_version }}"
          python_tag "${{ inputs.python_tag }}"
          git_tag "${{ inputs.git_tag }}"
          image_digest "${{ inputs.image_digest }}"
        EOF
        # ------------------------------------------------------------------
        cat ./outputs/vars

    - uses: actions/upload-artifact@v3
      with:
        name: vars
        path: outputs/
