---
name: save-artifact
description: save variables to artifact

inputs:
  python_version:
    description: Python version (<major.minor.*>)
    required: true
  python_tag:
    description: Python version tag (python-<major.minor>)
    required: true
  git_tag:
    description: Git short sha
    required: true
  # short_nametag:
  #   description: Image name and short tag (image:python-<major.minor>)
  #   required: true
  # long_nametag:
  #   description: Image name and long tag (image:python-<major.minor>-<sha>)
  #   required: true
  image_digest:
    description: Image digest
    required: true

runs:
  using: composite
  steps:
    - name: Save outputs to artifacts 💾
      id: outputs
      shell: bash
      run: |
        mkdir -p ./outputs
        cat << EOF >> ./outputs/vars
          python_version "${{ inputs.python_version }}"
          python_tag "${{ inputs.python_tag }}"
          git_tag "${{ inputs.git_tag }}"
          short_nametag "${{ inputs.short_nametag }}"
          long_nametag "${{ inputs.long_nametag }}"
          image_digest "${{ inputs.image_digest }}"
        EOF
        # ------------------------------------------------------------------
        cat ./outputs/vars

    - uses: actions/upload-artifact@v3
      with:
        name: vars
        path: outputs/
