---
name: Docker tests
description: Load and run tests from jupyter/docker-stacks (https://github.com/jupyter/docker-stacks)

inputs:
  registry:
    description: Image registry
    required: true
    type: string
  owner:
    description: Image repository owner
    required: true
    type: str
  image-name:
    description: Image name
    required: true
    type: string
  image-digest:
    description: Image digest
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Set Up Python 🐍

      uses: actions/setup-python@v4
      with:
        python-version: 3.x
      # if: ${{ inputs.platform == 'x86_64' }}

    - name: Install Dev Dependencies 📦
      run: |
        pip install --upgrade pip
        pip install --upgrade -r requirements-dev.txt
      shell: bash

    # # should be unneeded since using 'composite'
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull image 📥
      run: |
        docker pull ${{ inputs.registry }}/${{ inputs.owner }}/${{ inputs.image-name }}@${{ inputs.image-digest }}
      shell: bash

    ### Load and run tests from jupyter/docker-stacks (https://github.com/jupyter/docker-stacks)
    - name: Run tests ✅
      run: python3 -m tests.run_tests --short-image-name ${{ inputs.image }} --owner ${{ inputs.owner }}
      shell: bash
