name: base
channels:
  - conda-forge
  - districtdatalabs  ## for yellowbrick
  - defaults
dependencies:
# ### package managers
#   # - conda
#   # - mamba
#   - mamba_gator
  - pip
### Additional dependencies on top of `ds_env` sstandards
  - implicit
  - pynndescent
  - umap-learn
# ### pip
#   - pip:
#     - PACKAGE

# prefix: /opt/conda/
