---
name: build-image
# --- Description ------------------------------------------------------------
# Build image using docker buildx for multi-arch support
# ----------------------------------------------------------------------------

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      SOURCE_IMAGE:
        description: Parent/Source full image name (registry/image)
        required: true
        type: string
      IMAGE_NAME:
        description: Image name
        required: true
        type: string
      PYTHON_VERSION:
        description: python version
        required: true
        type: string
      PLATFORMS:
        description: Image platform architectures
        required: true
        type: string
      GH_REGISTRY:
        description: Github registry (ghcr.io/<OWNER>)
        required: true
        type: string
      OWNER:
        description: Registry name
        required: true
        type: string
    outputs:
      IMAGE_DIGEST: ${{ jobs.build-image-runner.outputs.IMAGE_DIGEST }}
      PYTHON_TAG: ${{ jobs.build-image-runner.outputs.PYTHON_TAG }}
      SHORT_NAMETAG: ${{ jobs.build-image-runner.outputs.SHORT_NAMETAG }}
      LONG_NAMETAG: ${{ jobs.build-image-runner.outputs.LONG_NAMETAG }}
  workflow_dispatch:


jobs:
  build-image-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 🛒
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry ✅
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to DockerHub ✅
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get current date 🗓
        id: date
        shell: bash
        run: |
          DATE=$(date +'%Y%m%d')
          echo "DATE: ${DATE}"
          echo "::set-output name=DATE::${DATE}"

      - name: Create tags 🏷
        id: tags
        shell: bash
        run: |
          GIT_SHA="${GITHUB_SHA:0:7}"
          PYTHON_TAG="python-$(echo ${PYTHON_VERSION/'.*'/}"
          SHORT_NAMETAG="${IMAGE_NAME}:${PYTHON_TAG}"
          LONG_NAMETAG="${IMAGE_NAME}:${PYTHON_TAG}-${GIT_SHA}"
          # ------------------------------------------------------------------
          echo "GIT_SHA: ${GIT_SHA}"
          echo "PYTHON_TAG: ${PYTHON_TAG}"
          echo "SHORT_NAMETAG: ${SHORT_NAMETAG}"
          echo "LONG_NAMETAG: ${LONG_NAMETAG}"
          # ------------------------------------------------------------------
          echo "::set-output name=GIT_SHA::${GIT_SHA}"
          echo "::set-output name=PYTHON_TAG::${PYTHON_TAG}"
          echo "::set-output name=SHORT_NAMETAG::${SHORT_NAMETAG}"
          echo "::set-output name=LONG_NAMETAG::${LONG_NAMETAG}"
        env:
          PYTHON_VERSION: ${{ inputs.PYTHON_VERSION }}
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}

      ### https://github.com/docker/build-push-action
      ### https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md
      - name: Build image 🛠
        id: build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ inputs.PLATFORMS }}
          context: src/${{ inputs.IMAGE_NAME }}
          # file: ./Dockerfile
          build-args: |
            SOURCE_IMAGE=${{ inputs.SOURCE_IMAGE }}
            PYTHON_VERSION=${{ inputs.PYTHON_VERSION }}
            GIT_COMMIT=${{ steps.tags.outputs.GIT_SHA }}
            BUILD_DATE=${{ steps.date.outputs.DATE }}
          # cache-from: type=gha
          cache-to: type=registry,ref=${{ inputs.GH_REGISTRY }}/${{ inputs.IMAGE_NAME }}:buildcache,mode=max
          push: true
          tags: |
            ${{ inputs.GH_REGISTRY }}/${{ steps.tags.outputs.SHORT_NAMETAG }}
            ${{ inputs.GH_REGISTRY }}/${{ steps.tags.outputs.LONG_NAMETAG }}

      - name: Inspect image digest 🔬
        shell: bash
        run: echo ${{ steps.build.outputs.digest }}

      - name: Inspect new image 🔬
        shell: bash
        run: |
          docker pull ${{ inputs.GH_REGISTRY }}/${{ inputs.IMAGE_NAME }}@${{ steps.build.outputs.digest }}

    outputs:
      IMAGE_DIGEST: ${{ steps.build.outputs.digest }}
      PYTHON_TAG: ${{ steps.tags.outputs.PYTHON_TAG }}
      SHORT_NAMETAG: ${{ steps.tags.outputs.SHORT_NAMETAG }}
      LONG_NAMETAG: ${{ steps.tags.outputs.LONG_NAMETAG }}
