---
name: test-image
# description:
# Load and run tests from jupyter/docker-stacks (https://github.com/jupyter/docker-stacks)

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      RUNS_ON:
        description: Github-hosted runner type
        required: true
        type: string
      REGISTRY:
        description: Source registry (ghcr.io/<OWNER> or docker.io/<OWNER>)
        required: true
        type: string
      OWNER:
        description: Registry name
        required: true
        type: string
      IMAGE_NAME:
        description: Image name
        required: true
        type: string
      IMAGE_DIGEST:
        description: SHA digest of image
        required: true
        type: string
  workflow_dispatch:


jobs:
  ### possible issues with macOS/arm64
  # https://github.com/github/roadmap/issues/528
  # https://github.com/actions/setup-python/issues/547
  test-image:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Checkout Repo 🛒
        uses: actions/checkout@v3

      - name: Set Up Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
        # if: ${{ inputs.platform == 'x86_64' }}

      - name: Install Dev Dependencies 📦
        shell: bash
        run: |
          pip install --upgrade pip
          pip install --upgrade -r requirements-dev.txt

      # # should be unneeded since using 'composite'
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image 📥
        shell: bash
        run: |
          docker pull ${{ inputs.registry }}/${{ inputs.owner }}/${{ inputs.image-name }}@${{ inputs.image-digest }}

      ### Load and run tests from jupyter/docker-stacks (https://github.com/jupyter/docker-stacks)
      - name: Run tests ✅
        shell: bash
        run: python3 -m tests.run_tests --short-image-name ${{ inputs.image }} --owner ${{ inputs.owner }}
