---
name: base
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  ### package managers
  - pip  # to prevent warnings
  ### Additional dependencies on top of `ds-env` sstandards
  - gensim
  - datasets # huggingface
  - nltk
  # - pattern==3.6.* # no longer dependency of gensim
  - pyldavis
  - pytorch
  - torchaudio
  - torchtext
  - torchvision
  - sacremoses # huggingface
  # - safetensors # huggingface; for gpu-based work
  - spacy
  - spacy-lookups-data
  - tokenizers # huggingface
  - transformers # huggingface

# prefix: /opt/conda/
