# docker-compose.yaml
# RUN: docker-compose --env-file
version: "3.7"

services:
  base_env:
    platform: linux/amd64
    build:
      context: .
      args:
        BASE_IMAGE: jupyter/minimal-notebook
        JUPYTER_VERSION: 3.3.0
        # PYTHON_VERSION: 3.9.*
        # BLAS: mkl  # uncomment to build with MKL
    image: base_env
    ports:
      - "8888:8888"
    # user: root
    environment:
      # - NB_USER=${NB_USER}
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      # - JUPYTER_TOKEN=jupyter_notebook_token
    command: start.sh jupyter lab

  # volumes:  # Optional, same as `docker volume create`

  # networks:  # Optional, same as `docker network create`

# ### build command
# docker build . \
#   --no-cache \
#   --build-arg BASE_IMAGE="jupyter/minimal-notebook" \
#   --build-arg JUPYTER_VERSION="3.3.0" \
#   --build-arg BUILD_DATE=$(date +'%Y-%m-%d') \
#   -t base_env:latest
