---
# docker-compose.yaml
# RUN: docker-compose --env-file
version: "3.7"

services:
  base-env:
    # platform: linux/amd64
    build:
      context: .
      args:
        SOURCE_IMAGE: jupyter/minimal-notebook:python-3.10
        PYTHON_VERSION: 3.10.*
        # BLAS: mkl  # uncomment to build with MKL
    image: base-env:python-3.10
    ports:
      - "8888:8888"
    # user: root
    environment:
      # - NB_USER=${NB_USER}
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      # - JUPYTER_TOKEN=jupyter_notebook_token
    command: start.sh jupyter lab

  # volumes:  # Optional, same as `docker volume create`

  # networks:  # Optional, same as `docker network create`

# ### build command
# docker build . \
#   --no-cache \
#   --build-arg SOURCE_IMAGE="jupyter/minimal-notebook" \
#   --build-arg PYTHON_VERSION="3.10.*" \
#   --build-arg BUILD_DATE=$(date +'%Y-%m-%d') \
#   -t base-env:latest
