---
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  ### package managers
  - mamba
  - pip
  ### core deps
  - cython
  - ipykernel
  - keyring
  ### JupyterLab "OS-level" extensions
  - ipywidgets
  # - jupyter_contrib_nbextensions
  # - jupyter_nbextensions_configurator
  - jupyterlab>=3.6,<4
  - jupyterlab_code_formatter
  - jupyterlab_widgets # backend for ipywidgets
  # - jupyterlab-flake8
  - jupyterlab-git
  - jupytext
  - widgetsnbextension
  ### linting/formatting
  - black
  - ruff
  ### testing
  - pytest
  - pytest-asyncio
  ### utilities
  - pyyaml
# prefix: /opt/conda/
