name: base
channels:
  - conda-forge
  - districtdatalabs  ## for yellowbrick
  - defaults
dependencies:
# ### package managers
#   # - conda
#   # - mamba
#   - mamba_gator
#   - pip
### Additional dependencies on top of `ds_env` sstandards
  - beautifulsoup4
  - graphviz
  - lxml
  - mlxtend
  - networkx
  - python-graphviz
  - pydotplus
  - requests
  - scrapy
  - selenium
# ### pip
#   - pip:
#     - markovclick
#     - retentioneering
### markovclick deps
### retentioneering deps
  - vega
  - pymongo
  - umap-learn



# prefix: /opt/conda/
