---
name: build-and-tag
# description:
# builds (multi-arch) docker image and caches to github registry (via build-image.yaml workflow)
# runs test (via test-image.yaml workflow)
# retags and pushes to docker registry (via tag-image.yaml workflow)

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      SOURCE_IMAGE:
        description: Parent/Source image name (repository/name)
        required: true
        type: string
      IMAGE_NAME:
        description: Image name
        required: true
        type: string
      PLATFORMS:
        description: Image platform architectures
        required: true
        type: string
      PYTHON_VERSION:
        description: python version
        required: true
        type: string
      GH_REGISTRY:
        description: Github registry (ghcr.io/<OWNER>)
        required: true
        type: string
      D_REGISTRY:
        description: Docker registry (docker.io/<OWNER>)
        required: true
        type: string
      OWNER:
        description: Registry name
        required: true
        type: string
  workflow_dispatch:

env:
  # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
  BRANCH_NAME: ${{ GITHUB_HEAD_REF || GITHUB_REF_NAME }}

jobs:

  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: [3.8.*, 3.9.*, 3.10.*]

    steps:
      - name: Checkout Repo 🛒
        uses: actions/checkout@v3

      - name: Build image 🛠
        id: build
        uses: ./.github/workflows/build-image.yaml
        with:
          SOURCE_IMAGE: ${{ inputs.SOURCE_IMAGE }}
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
          PLATFORMS: ${{ inputs.PLATFORMS }}
          PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
          GH_REGISTRY: ${{ inputs.GH_REGISTRY }}
          OWNER: ${{ inputs.OWNER }}

    outputs:
      # IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
      IMAGE_DIGEST: ${{ steps.build.outputs.IMAGE_DIGEST }}
      PYTHON_TAG: ${{ steps.build.outputs.PYTHON_TAG }}
      # SHA_TAG: ${{ steps.build.outputs.SHA_TAG }}
      SHORT_NAMETAG: ${{ steps.build.outputs.SHORT_NAMETAG }}
      LONG_NAMETAG: ${{ steps.build.outputs.LONG_NAMETAG }}


  ### possible issues with macOS/arm64
  # https://github.com/github/roadmap/issues/528
  # https://github.com/actions/setup-python/issues/547
  test-image:
    needs: build-image
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo 🛒
        uses: actions/checkout@v3

      - name: Test image 🧪
        uses: ./.github/workflows/test-image.yaml
        with:
          RUNS_ON: ${{ matrix.os }}
          REGISTRY: ${{ inputs.GH_REGISTRY }}
          OWNER: ${{ env.OWNER }}
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
          IMAGE_DIGEST: ${{ needs.build-image.outputs.IMAGE_DIGEST }}

      # # use workflow instead of action
      # - name: Test image 🧪
      #   uses: ./.github/actions/docker-test
      #   with:
      #     registry: ${{ inputs.GH_REGISTRY }}
      #     owner: ${{ inputs.OWNER }}
      #     image-name: ${{ needs.build-image.outputs.IMAGE_NAME }}
      #     image-digset: ${{ needs.build-image.outputs.IMAGE_DIGEST }}


  ### Push to DockerHub if main branch / "release"
  dockerhub-tag-push:
    runs-on: ubuntu-latest
    needs: test-image

    # push to registry on main branch only
    # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
    if: ${{ BRANCH_NAME }} == 'main'
    steps:
      - name: Tag and Push to Docker 🐳
        uses: ./.github/workflows/tag-image.yaml
        with:
          GH_REGISTRY: ${{ inputs.GH_REGISTRY }}
          D_REGISTRY: ${{ inputs.D_REGISTRY }}
          IMAGE_NAME: ${{ needs.build-image.outputs.IMAGE_NAME }}
          IMAGE_DIGEST: ${{ needs.build-image.outputs.IMAGE_DIGEST }}
          SHORT_NAMETAG: ${{ needs.build-image.outputs.SHORT_NAMETAG }}
          LONG_NAMETAG: ${{ needs.build-image.outputs.LONG_NAMETAG }}
