---
name: Build container stack for particular tag

on: # yamllint disable-line rule:truthy
  schedule:
    # # at: 01:00 on the first of every month
    - cron: "0 1 1 * *"
  pull_request:
    paths-ignore:
      # - ".github/**"
      - docs/**
      - scripts/**
      - '*.md'
      - '**/.gitignore'
      - docker-compose.yaml
      - LICENSE
  push:
    branches:
      - main
    paths-ignore:
      # - ".github/**"
      - docs/**
      - scripts/**
      - '*.md'
      - '**/.gitignore'
      - docker-compose.yaml
      - LICENSE
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  # group: ${{ github.ref }}
  cancel-in-progress: true


env:
  GH_REGISTRY: ghcr.io/ninerealmlabs
  D_REGISTRY: docker.io/ninerealmlabs
  OWNER: ninerealmlabs


jobs:
  base-env:
    uses: ./.github/workflows/build-test-tag.yaml
    with:
      SOURCE_IMAGE: jupyter/minimal-notebook
      IMAGE_NAME: base-env
      PLATFORMS: "linux/amd64,linux/arm64"
      GH_REGISTRY: ${{ env.GH_REGISTRY }}
      D_REGISTRY: ${{ env.D_REGISTRY }}
      OWNER: ${{ env.OWNER }}
    # if: github.repository == 'ninerealmlabs/docker-jupyter-stacks'

  ds-env:
    uses: ./.github/workflows/build-test-tag.yaml
    with:
      SOURCE_IMAGE: ghcr.io/ninerealmlabs/base-env
      IMAGE_NAME: ds-env
      PLATFORMS: "linux/amd64,linux/arm64"
      GH_REGISTRY: ${{ env.GH_REGISTRY }}
      D_REGISTRY: ${{ env.D_REGISTRY }}
      OWNER: ${{ env.OWNER }}
    needs: [base-env]
    # if: github.repository == 'ninerealmlabs/docker-jupyter-stacks'

  nlp-env:
    uses: ./.github/workflows/build-test-tag.yaml
    with:
      SOURCE_IMAGE: ghcr.io/ninerealmlabs/ds-env
      IMAGE_NAME: nlp-env
      PLATFORMS: "linux/amd64,linux/arm64"
      GH_REGISTRY: ${{ env.GH_REGISTRY }}
      D_REGISTRY: ${{ env.D_REGISTRY }}
      OWNER: ${{ env.OWNER }}
    needs: [ds-env]
    # if: github.repository == 'ninerealmlabs/docker-jupyter-stacks'

  ts-env:
    uses: ./.github/workflows/build-test-tag.yaml
    with:
      SOURCE_IMAGE: ghcr.io/ninerealmlabs/ds-env
      IMAGE_NAME: ts-env
      PLATFORMS: "linux/amd64,linux/arm64"
      GH_REGISTRY: ${{ env.GH_REGISTRY }}
      D_REGISTRY: ${{ env.D_REGISTRY }}
      OWNER: ${{ env.OWNER }}
    needs: [ds-env]
    # if: github.repository == 'ninerealmlabs/docker-jupyter-stacks'

  web-env:
    uses: ./.github/workflows/build-test-tag.yaml
    with:
      SOURCE_IMAGE: ghcr.io/ninerealmlabs/ds-env
      IMAGE_NAME: web-env
      PLATFORMS: "linux/amd64,linux/arm64"
      GH_REGISTRY: ${{ env.GH_REGISTRY }}
      D_REGISTRY: ${{ env.D_REGISTRY }}
      OWNER: ${{ env.OWNER }}
    needs: [nlp-env]
    # if: github.repository == 'ninerealmlabs/docker-jupyter-stacks'
