name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
#       - ".github/**"
      - "*.md"
      - "LICENSE"

jobs:
  base_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      ### used for multi-arch builds
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      ### https://github.com/docker/build-push-action
      ### https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: src/base_env/
          # file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          # platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=jupyter/minimal-notebook:latest
            PYTHON_VERSION=3.8.*
          load: true  # make available in gha workflow for `docker` commands
          # outputs: type=image
          outputs: type=docker,dest=/tmp/base_env.tar  # for `upload-artifact` action
          push: false  # ci build only
          tags: base_env:ci
          ### https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        ### Temp fix for exploding cache
        ### https://github.com/docker/build-push-action/issues/252
        ### https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Run Docker container
        run: docker run base_env:ci

      #   ### https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md
      #   ### Each job is isolated in its own runner, so can't use newly-built image between jobs
      #   ### Instead, pass data between jobs in a workflow using the actions/upload-artifact and actions/download-artifact
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: myimage
      #     path: /tmp/base_env.tar

  # ds_env:
  #   needs: base_env
      # - name: Download new base_env
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: base_env
      #     path: /tmp
      # - name: Load image
      #   run: |
      #     docker load --input /tmp/base_env.tar
      #     docker image ls -a

  # nlp_env:
  #   needs: [base_env, ds_env]
  # recommender_env:
  #   needs: [base_env, ds_env]
  # web_env:
  #   needs: [base_env, ds_env]
  # pytorch_env:
  #   needs: [base_env, ds_env]
  # forecast_env:
  #   needs: [base_env, ds_env, pytorch_env]