---
name: ds-env

on: # yamllint disable-line rule:truthy
  # workflow_dispatch:
  #   inputs:
  #     source_image:
  #       description: Parent/Source image name (repository/name)
  #       required: true
  #       type: string
  #     source_tag:
  #       description: Tag digest of source image
  #       required: true
  #       type: string
  #       default: 'latest'
  #     source_digest:
  #       description: SHA digest of source image
  #       required: false
  #       type: string
  #       default: ''
  #     python_version:
  #       description: Python version (<major.minor.*>)
  #       required: true
  #       type: string
  workflow_run:
    workflows: [base-env]
    types:
      - completed

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  # group: ${{ github.workflow }}-${{ github.ref }}
  # group: ${{ github.ref }}
  cancel-in-progress: true

# define static vars here
env:
  image_name: ds-env
  platforms: "linux/amd64,linux/arm64"
  gh_registry: ghcr.io/ninerealmlabs
  d_registry: docker.io/ninerealmlabs
  owner: ninerealmlabs
  ### source vars from artifact pass
  # source_image: base-env
  # source_tag: latest
  # source_digest: ''

jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]

    # continue-on-error: true
    # if: github.repository == 'ninerealmlabs/docker-jupyter-stacks'
    if: |
      ${{ github.event.workflow_run.conclusion == 'success' }}
      || ${{ github.event.workflow_dispatch }}
    steps:
      ### --- Prep -----------------------------------------------------------
      # https://stackoverflow.com/questions/70483902/how-to-actually-clean-up-the-repository-on-self-hosted-runner-after-github-actio
      - name: Cleanup build folder 🧹
        shell: bash
        run: |
          cd ${{ github.workspace }}
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout Repo 🛒
        uses: actions/checkout@v3
        # allow workflow_run to trigger on non-main branch:
        # https://stackoverflow.com/questions/63343937/how-to-use-the-github-actions-workflow-run-event
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # if workflow_run
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Read passed inputs from artifact 📖
        id: source_inputs
        uses: ./.github/actions/read-artifact-action
        # with:
        #   artifact_name: vars

      - if: ${{ github.event.workflow_dispatch }}
        name: Read passed inputs 📖
        id: source_inputs
        shell: bash
        run: |
          echo "SOURCE_IMAGE: ${SOURCE_IMAGE}"
          echo "SOURCE_TAG: ${SOURCE_TAG}"
          echo "SOURCE_DIGEST: ${SOURCE_DIGEST}"
          echo "PYTHON_VERSION: ${PYTHON_VERSION}"
          # ------------------------------------------------------------------
          echo "source_image=${{ inputs.source_image }}" >> $GITHUB_OUTPUT
          echo "source_tag=${{ inputs.source_tag }}" >> $GITHUB_OUTPUT
          echo "source_digest=${{ inputs.source_digest }}" >> $GITHUB_OUTPUT
          echo "python_version=${{ inputs.python_version }}" >> $GITHUB_OUTPUT
        env:
          SOURCE_IMAGE: ${{ inputs.source_image }}
          SOURCE_TAG: ${{ inputs.source_tag }}
          SOURCE_DIGEST: ${{ inputs.source_digest }}
          PYTHON_VERSION: ${{ inputs.python_version }}

      - name: Login to GitHub Container Registry ✅
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ### --- Build ----------------------------------------------------------
      - name: Build Image 🛠
        id: build
        uses: ./.github/actions/build-image-action
        with:
          source_image: ${{ steps.source_inputs.outputs.image_name }}
          source_tag: ${{ steps.source_inputs.outputs.python_tag }}
          source_digest: ${{ steps.source_inputs.outputs.image_digest }}
          image_name: ${{ env.image_name }}
          python_version: ${{ steps.source_inputs.outputs.python_version }}
          platforms: ${{ env.platforms }}
          gh_registry: ${{ env.gh_registry }}
          owner: ${{ env.owner }}

      # ### --- Test -----------------------------------------------------------
      # - name: Test Image 🧪
      #   id: test
      #   uses: ./.github/actions/test-image-action
      #   with:
      #     gh_registry: ${{ env.gh_registry }}
      #     owner: ${{ env.owner }}
      #     image_name: ${{ env.image_name }}
      #     image_digest: ${{ steps.build.outputs.digest }}

      ### --- Pass -----------------------------------------------------------
      - name: Save outputs to artifacts 💾
        uses: ./.github/actions/save-artifact-action
        with:
          image_name: ${{ env.image_name }}
          python_version: ${{ steps.source_inputs.outputs.python_version }}
          python_tag: ${{ steps.build.outputs.python_tag }}
          git_tag: ${{ steps.build.outputs.git_tag }}
          image_digest: ${{ steps.build.outputs.digest }}


      ### --- Push to Dockerhub ----------------------------------------------
      # push to registry on main branch only
      - name: Login to DockerHub ✅
        # if: github.ref_name == 'main'
        if: github.event.workflow_run.head_branch == 'main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # allow workflow_run to trigger on non-main branch:
      # https://stackoverflow.com/questions/63343937/how-to-use-the-github-actions-workflow-run-event
      # - if: github.ref_name == 'main'
      - if: github.event.workflow_run.head_branch == 'main'
        name: Tag & Push image to docker 🏷
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ${{ env.gh_registry }}/${{ env.image_name }}@${{ steps.build.outputs.digest }}
          dst: |
            ${{ env.d_registry }}/${{ env.image_name }}:${{ steps.build.outputs.python_tag }}
            ${{ env.d_registry }}/${{ env.image_name }}:${{ steps.build.outputs.python_tag }}-${{ steps.build.outputs.git_tag }}
