name: ds_env-CI

on:
  workflow_run:
    # trigger after base_env CI completes
    workflows: ["base_env-CI"]
    branches:
      - main
      - 'develop/**'
    types:
      - completed

env:
  PLATFORMS: linux/amd64  #,linux/arm64
  GH_REGISTRY: ghcr.io/ninerealmlabs
  D_REGISTRY: ninerealmlabs
  BASE_IMAGE: base_env

jobs:
  ### NOTE: job name MUST be equivalent to image name and directory
  ds_env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7.*, 3.8.*, 3.9.*]

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      ### download artifact
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Required, workflow file name or ID
          workflow: base_env-ci.yml
          # Optional, will use specified workflow run
          run_id: ${{ github.event.workflow_run.run_id }}
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: ${{ env.BASE_IMAGE }}-${{ github.event.workflow_run.run_id }}
          path: WFRUN_INFO

      - name: Parse artifact
        id: info
        run: |
          WORKFLOW=$(sed -n 's/^WORKFLOW://p' WFRUN_INFO)
          RUN_ID=$(sed -n 's/^RUN_ID://p' WFRUN_INFO)
          RUN_NUM=$(sed -n 's/^RUN_NUM://p' WFRUN_INFO)
          REF=$(sed -n 's/^REF://p' WFRUN_INFO)
          SHA=$(sed -n 's/^SHA://p' WFRUN_INFO)
          echo "WORKFLOW: ${WORKFLOW}"
          echo "RUN_ID: ${RUN_ID}"
          echo "WORKFLOW: ${WORKFLOW}"
          echo "RUN_NUM: ${RUN_NUM}"
          echo "REF: ${REF}"
          echo "SHA: ${SHA}"
          echo "::set-output name=workflow::${WORKFLOW}"
          echo "::set-output name=run_id::${RUN_ID}"
          echo "::set-output name=run_num::${RUN_NUM}"
          echo "::set-output name=ref::${REF}"
          echo "::set-output name=sha::${SHA}"

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.info.outputs.sha }}
          fetch-depth: 0

      ### used for multi-arch builds
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: |
          DATE=$(date +'%Y%m%d')
          echo "DATE: ${DATE}"
          echo "::set-output name=date::${DATE}"

      - name: Create tags
        id: tag
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          INFO_REF: ${{ steps.info.outputs.ref }}
          INFO_SHA: ${{ steps.info.outputs.sha }}
        run: |
          TAG_VERSION=${PYTHON_VERSION}
          if [[ ${TAG_VERSION: -1} == "*" ]]; then
              TAG_VERSION=${TAG_VERSION: 0:${#TAG_VERSION}-2}
          fi
          BRANCH=$(echo ${INFO_REF} | sed s'|refs/heads/||' | sed s'|/|.|')
          SHA=${INFO_SHA:0:7}
          FULLTAG="python-${TAG_VERSION}-${BRANCH}-${SHA}"
          PRODTAG="python-${TAG_VERSION}-${SHA}"
          #---
          echo "TAG_VERSION: ${TAG_VERSION}"
          echo "FULLTAG: ${FULLTAG}"
          echo "PRODTAG: ${PRODTAG}"
          #---
          echo "::set-output name=pythontag::${TAG_VERSION}"
          echo "::set-output name=fulltag::${FULLTAG}"
          echo "::set-output name=prodtag::${PRODTAG}"

      # - name: Create tag from branch
      #   id: branch
      #   run: |
      #     BRANCH=$(${{ steps.info.outputs.ref }} | sed s'|/|.|')  # BRANCH=$(git rev-parse --abbrev-ref HEAD | sed s'|/|.|')
      #     echo "BRANCH: ${BRANCH}"
      #     echo "::set-output name=branch::${BRANCH}"

      # - name: Create tag from sha
      #   id: sha
      #   run: |
      #     GIT_SHA=$(git rev-parse --short HEAD)
      #     echo "GIT_SHA: ${GIT_SHA}"
      #     echo "::set-output name=sha::${GIT_SHA}"

      # - name: Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     # list of Docker images to use as base name for tags
      #     images: |
      #       ${{ env.GH_REGISTRY }}/${{ github.job }}
      #     tags: |
      #       type=sha
      #       type=sha,prefix=python-${{ steps.tag.outputs.tag }}-

      ### https://github.com/docker/build-push-action
      ### https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          # platforms: ${{ env.PLATFORMS }}
          context: src/${{ github.job }}/
          # file: ./Dockerfile
          build-args: |
            BASE_IMAGE=${{ env.GH_REGISTRY }}/${{ env.BASE_IMAGE }}:${{ steps.tag.outputs.fulltag }}
            PYTHON_VERSION=${{ matrix.python }}
            BUILD_DATE=${{ steps.date.outputs.date }}
          no-cache: true
          ### Each job is isolated in its own runner, so can't share newly-built image directly between jobs
          ### Instead, push to **github** image repo
          push: true
          tags: |
            ${{ env.GH_REGISTRY }}/${{ github.job }}:${{ steps.tag.outputs.pythontag }}
            ${{ env.GH_REGISTRY }}/${{ github.job }}:${{ steps.tag.outputs.fulltag }}
      #     ${{ steps.meta.outputs.tags }}

      # ### https://github.com/marketplace/actions/docker-buildx-bake
      # ### https://github.com/crazy-max/docker-buildx-bake-demo/
      # - name: Build image
      #   id: docker_bake
      #   uses: docker/bake-action@v1.5
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     files: src/${{ github.job }}/docker-compose.yml
      #     no-cache: true
      #     set: |
      #       *.platform=${{ env.PLATFORMS }}
      #       *.args.BASE_IMAGE=${{ env.GH_REGISTRY }}/${{ env.BASE_IMAGE }}:python-${{ steps.tag.outputs.tag }}-${{ steps.ref.outputs.ref }}-${{ steps.sha.outputs.sha }}
      #       *.args.PYTHON_VERSION=${{ matrix.python }}
      #       *.args.BUILD_DATE=${{ steps.date.outputs.date }}
      #       *.tags=${{ env.GH_REGISTRY }}/${{ github.job }}:python-${{ steps.tag.outputs.tag }}
      #       *.tags=${{ env.GH_REGISTRY }}/${{ github.job }}:python-${{ steps.tag.outputs.tag }}-${{ steps.ref.outputs.ref }}-${{ steps.sha.outputs.sha }}
      #     push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Inspect new image
        run: |
          docker pull ${{ env.GH_REGISTRY }}/${{ github.job }}:${{ steps.tag.outputs.fulltag }}
          docker inspect ${{ env.GH_REGISTRY }}/${{ github.job }}:${{ steps.tag.outputs.fulltag }}

###############################################################################
# Save run info as artifact & upload
###############################################################################
      - name: Preserve run info
        env:
          WORKFLOW: ${{ steps.info.outputs.workflow }}
          RUN_ID: ${{ steps.info.outputs.run_id }}
          RUN_NUM: ${{ steps.info.outputs.run_num }}
          REF: ${{ steps.info.outputs.ref }}
          SHA: ${{ steps.info.outputs.sha }}
        run: |
          touch INFO
          echo "WORKFLOW:${GITHUB_WORKFLOW}" >> INFO
          echo "RUN_ID:${GITHUB_RUN_ID}" >> INFO
          echo "RUN_NUM:${GITHUB_RUN_NUMBER}" >> INFO
          echo "REF:${GITHUB_REF}" >> INFO
          echo "SHA:${GITHUB_REF}" >> INFO

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}-${{ github.run_id }}
          path: INFO
          retention-days: 1


###############################################################################
# Push to DockerHub if main branch / "release"
###############################################################################

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # copy image from ghcr to dockerhub
      - name: Push image to alternate registries
        # push to registry on main branch only
        if: github.event.workflow_run.head_branch == 'refs/heads/main'
        uses: akhilerm/tag-push-action@v1.1.0
        with:
          src: ${{ env.GH_REGISTRY }}/${{ github.job }}:${{ steps.tag.outputs.fulltag }}
          dst: |
            ${{ env.D_REGISTRY }}/${{ github.job }}:${{ steps.tag.outputs.pythontag }}
            ${{ env.D_REGISTRY }}/${{ github.job }}:${{ steps.tag.outputs.prodtag }}