---
name: test-image
# description:
# Gets image from github registry, retags, and pushes to docker registry

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      GH_REGISTRY:
        description: Github registry (ghcr.io/<OWNER>)
        required: true
        type: string
      D_REGISTRY:
        description: Docker registry (docker.io/<OWNER>)
        required: true
        type: string
      IMAGE_NAME:
        description: Image name
        required: true
        type: string
      IMAGE_DIGEST:
        description: SHA digest of image
        required: true
        type: string
      SHORT_NAMETAG:
        description: Image name and short tag (image:python-<major.minor>)
        required: true
        type: string
      LONG_NAMETAG:
        description: Image name and long tag (image:python-<major.minor>-<sha>)
        required: true
        type: string
  workflow_dispatch:


jobs:
  ### possible issues with macOS/arm64
  # https://github.com/github/roadmap/issues/528
  # https://github.com/actions/setup-python/issues/547
  tag-image:
    runs-on: ubuntu-latest

    # push to registry on main branch only
    steps:
      - name: Login to DockerHub ✅
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # copy image from ghcr to dockerhub
      - name: Push image to alternate registries 💾
        # uses: akhilerm/tag-push-action@main
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ${{ inputs.GH_REGISTRY }}/${{ inputs.IMAGE_NAME }}@${{ inputs.IMAGE_DIGEST }}
          dst: |
            ${{ inputs.D_REGISTRY }}/${{ inputs.SHORT_NAMETAG }}
            ${{ inputs.D_REGISTRY }}/${{ inputs.LONG_NAMETAG }}
