---
name: (Re)Tag image and push to registry
description: Pull image from github registry, retags, and pushes to (docker) registry

inputs:
  gh_registry:
    description: Github registry (ghcr.io/<owner>)
    required: true
  d_registry:
    description: Docker registry (docker.io/<owner>)
    required: true
  image_name:
    description: Image name
    required: true
  image_digest:
    description: SHA digest of image
    required: true
  short_nametag:
    description: Image name and short tag (image:python-<major.minor>)
    required: true
  long_nametag:
    description: Image name and long tag (image:python-<major.minor>-<sha>)
    required: true

runs:
  using: composite
  steps:
    ### should completed outside of Action and apply inside
    ### since 'using: composite'
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #
    # - name: Login to DockerHub ✅
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USER }}
    #     password: ${{ secrets.DOCKER_TOKEN }}

    # copy image from ghcr to dockerhub
    - name: Push image to alternate registries 💾
      uses: akhilerm/tag-push-action@v2.1.0
      with:
        src: ${{ inputs.gh_registry }}/${{ inputs.image_name }}@${{ inputs.image_digest }}
        dst: |
          ${{ inputs.d_registry }}/${{ inputs.short_nametag }}
          ${{ inputs.d_registry }}/${{ inputs.long_nametag }}
